### ISSUE TITLE
The site is down (again)

### ISSUE THREAD

**Issue by brillout** [kitten/trygql.dev#4]
Hi there,

Sorry to disturb again, but I thought you may want to know that https://trygql.formidable.dev/ is down again.

(It's fine for vite-plugin-ssr's CI, I'll just move to another GraphQL endpoint.)

**Comment by gksander** [comment]
Hi @brillout – we merged #5 the other week as an attempt to keep the site from "falling down". Since then, I haven't seen fall down. I'm going to mark this as resolved, but if the site begins to have troubles again, we'll reopen this.
